import React, { Component } from 'react';
import { Scrollbars } from 'react-custom-scrollbars';
import style from './style.scss'

class MainContainer extends Component {
  render() {
    return (
      <div className={style.container}>
        <Scrollbars >
          <p className={style.text}>
            <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita blanditiis necessitatibus quaerat tempora distinctio, accusamus inventore ipsam ad rem nostrum aut earum, numquam dignissimos ea nobis corrupti voluptates incidunt nisi.</div>
            <div>Blanditiis ex deserunt, eaque, velit, minus aperiam sint doloremque sequi tempore, obcaecati accusantium perspiciatis nisi officiis eveniet quasi. Error et eos quas beatae fugiat similique illum odit maiores ea nostrum.</div>
            <div>Tempore quos molestiae eos, harum blanditiis, neque architecto modi dolor, aliquid cum nesciunt rerum. Nemo debitis mollitia ad, est praesentium numquam deleniti, facere reiciendis qui libero natus fugit dignissimos nihil.</div>
            <div>Soluta nemo error veniam esse maxime in dignissimos mollitia rem sit illo cum, obcaecati pariatur adipisci incidunt provident unde, maiores. Placeat laboriosam error hic, ratione odit adipisci quisquam temporibus magni!</div>
            <div>Perspiciatis nemo quaerat possimus, ipsum provident voluptatem ducimus, reprehenderit nam quae harum cumque vel neque et doloremque, natus vitae fugit quis odio! Dignissimos harum dolores nulla illum distinctio deleniti sunt.</div>
            <div>Accusamus ut consectetur, recusandae quae sequi ad dolor incidunt minus libero id, suscipit distinctio veniam possimus. Natus soluta inventore iste, nulla earum saepe nostrum tenetur, dolorum, ipsa, sequi modi obcaecati.</div>
            <div>Veritatis quibusdam neque vero nemo nam ipsa ab voluptas quos deserunt. Minima aut illum debitis vel sapiente doloremque ut ad accusamus magni maiores. Quos voluptatem iure, animi ducimus quidem sunt!</div>
            <div>Laborum ex tempora porro cupiditate inventore! Esse minima deleniti ad veritatis odio quos neque porro hic pariatur, culpa sunt tempore, autem natus quibusdam modi laboriosam delectus quo consectetur iusto. Placeat?</div>
            <div>Nulla explicabo iure, dolore magni excepturi maiores doloremque nesciunt temporibus reiciendis. Laborum aspernatur, soluta numquam ipsum autem, distinctio quod tempore! Ea error, sed pariatur officiis iure facilis harum, beatae eius.</div>
            <div>Reprehenderit nam, qui unde beatae cum, tempora. A dolores incidunt facere doloremque vitae, beatae laborum praesentium placeat esse illum, nisi odit debitis. Repudiandae earum eos, dolores enim accusamus sapiente, vero.</div>
            <div>Commodi, sit eius perferendis ea expedita, officia! Corporis tempora, eaque hic iste omnis soluta eveniet nam dolores aperiam dolorem incidunt, dolor nulla modi aspernatur aliquid magni unde veritatis, a nostrum!</div>
            <div>A eaque voluptates, debitis voluptas sed, quidem expedita tempora culpa eveniet molestias quisquam est quod labore modi odit nihil natus! Ducimus debitis esse labore eos odit nulla non eveniet, laudantium!</div>
            <div>Neque, nostrum. Mollitia perspiciatis natus incidunt exercitationem deserunt autem nemo tempore necessitatibus cumque? At odio iste quos mollitia sequi omnis deleniti, laboriosam nihil eligendi inventore, quam atque magni corporis ex?</div>
            <div>Adipisci voluptatem porro ab laudantium dolorem deserunt, corporis maxime quibusdam ipsam, quidem consectetur sed ducimus iste! Voluptates iure animi rem, veritatis ipsam maiores nemo architecto modi, voluptatum asperiores beatae doloribus.</div>
            <div>Repellendus distinctio praesentium quos. Repellendus vitae architecto veritatis soluta velit error odio, modi, ullam culpa sapiente aliquid dolore voluptates optio delectus eum odit reiciendis. Impedit id perferendis placeat incidunt exercitationem!</div>
            <div>Sed pariatur, cumque officia delectus, expedita repellendus cupiditate blanditiis velit asperiores modi nobis quaerat optio id recusandae, nesciunt corporis vel? Quas molestiae, aut omnis itaque laboriosam magni voluptate eveniet suscipit?</div>
            <div>Illo ipsum id hic neque repellendus nisi sint doloremque dicta tempore vero aliquid, veniam perferendis eaque mollitia facere repellat quo, pariatur in. Ab blanditiis voluptate, rem eligendi sint velit quam!</div>
            <div>Ut totam distinctio sunt, est! Aperiam velit ab libero provident, quas architecto molestiae laborum. Eveniet voluptatem nam provident mollitia maiores ullam officiis quia nihil, fugit, sint nulla in itaque, suscipit.</div>
            <div>Neque aspernatur qui nostrum voluptatibus adipisci ex tempora omnis odio accusantium? Deserunt ea dolores, aspernatur possimus earum at, obcaecati veniam similique minus atque sequi esse natus sapiente. Assumenda quia, ducimus.</div>
            <div>Aliquid error soluta aspernatur vel odio velit aperiam, quidem pariatur labore minus. Voluptas fuga illo ducimus tempore assumenda magnam quasi, accusamus veritatis molestiae minus animi nisi explicabo natus fugiat cupiditate.</div>
            <div>Expedita mollitia illum minima doloremque officiis amet iure, ipsum nobis inventore deleniti ipsa qui natus perferendis consectetur sit illo consequatur alias corporis quaerat suscipit eligendi. Quibusdam quia saepe ipsa repudiandae.</div>
            <div>Odit nostrum quo sint perspiciatis qui tempora, cupiditate facere delectus quod recusandae illo! Expedita nihil quaerat facere nisi accusantium, alias, earum esse. Repellendus sequi corrupti, molestias placeat quidem officia sint.</div>
            <div>Neque, odio, accusamus? Porro officiis tenetur, mollitia unde ab dolore amet maiores quas repudiandae minima iure quia at, dignissimos quaerat, enim facilis eligendi numquam quam? Culpa quas nostrum, vel laboriosam?</div>
            <div>Ab consequatur saepe repellat necessitatibus aut. Laboriosam, tempora nostrum. Facere alias, veritatis. Nesciunt ratione esse neque voluptates exercitationem sed necessitatibus eum repellendus nostrum, maiores, error placeat, temporibus ex tempore nisi.</div>
            <div>Ad inventore molestiae, ipsa minus soluta sint exercitationem pariatur laborum adipisci, dolore hic, cumque eos. Molestiae, beatae voluptatibus cum quae amet in dolorum vitae, ex deserunt porro, accusamus suscipit esse.</div>
            <div>Cupiditate nobis optio aut, voluptatum dolorem est eos sint ad, minus aliquid excepturi molestiae. Inventore voluptas fugiat quia in quas voluptatum culpa quos alias tempore, mollitia fugit deserunt dolorum non.</div>
            <div>Veniam placeat, hic eos ipsa, provident odio enim error iste magni iusto nulla sint officiis omnis ipsam commodi minima, obcaecati tempora esse. Cum laudantium, expedita illum quasi recusandae blanditiis doloribus?</div>
            <div>Voluptates fugiat modi ab. Voluptates, est voluptatibus. Molestiae repellendus distinctio natus voluptates quae delectus cumque architecto voluptatem impedit magni earum corporis aut, ex, laboriosam, tenetur facilis! Repellat, rem! Quidem, recusandae.</div>
            <div>Quae, consectetur voluptatum vitae, aliquam labore nam harum debitis tempore cum facere, expedita odio architecto incidunt ullam necessitatibus minus. Repudiandae quaerat possimus quo, dicta alias pariatur deserunt. Rerum, corrupti velit?</div>
            <div>Enim atque repellendus ab molestias vitae fugiat quos quaerat blanditiis veniam. Laudantium nihil autem voluptates veniam. Obcaecati dolore atque expedita dolorum harum provident ad eveniet ipsa molestiae, ab, suscipit, ratione!</div>
            <div>Dolores laborum iure ut facere velit, nulla ea quis vel voluptatem deserunt magni, repellat ex maiores laboriosam itaque ipsum, molestias voluptatum. Magni pariatur quos dolor animi voluptatum corporis repellat, eum.</div>
            <div>Debitis, quod, commodi! Neque molestiae quibusdam reiciendis ipsum perferendis dolorum quas eveniet veritatis, voluptatum placeat amet ex, nobis, reprehenderit suscipit fugit beatae natus enim nam velit tempora aperiam laborum maiores?</div>
            <div>Minima accusamus perferendis nulla molestiae laboriosam quidem, itaque autem temporibus numquam nisi inventore illum labore animi ullam, ducimus possimus odio, odit sunt dicta. Ut unde id mollitia molestiae. Dolores, quasi!</div>
            <div>Quam rem corrupti deleniti, dolorem perspiciatis quas! Ab facilis consequatur qui iusto dolor adipisci voluptate cum autem asperiores magni, nostrum delectus sit libero eum fuga voluptas necessitatibus alias optio mollitia.</div>
            <div>Reiciendis excepturi rem totam, quam provident cum deserunt maxime. Nam, vero autem incidunt perspiciatis accusantium soluta cumque! Fugit pariatur libero, expedita optio alias non debitis inventore, voluptatum beatae voluptatibus qui.</div>
            <div>Quo provident, enim alias excepturi a molestiae labore nisi, nostrum sed consequuntur minima. Accusantium iste, quod iure, aspernatur quidem ea culpa sint corporis temporibus doloribus nemo rem, eius impedit enim?</div>
            <div>Delectus id itaque, tempora provident molestias neque expedita, vero quasi! Est, libero omnis molestias nostrum praesentium reiciendis maiores deleniti illo. Officia animi repellat nemo? Architecto, distinctio. Est dolores soluta autem.</div>
            <div>Tempora numquam non quae pariatur? Aperiam possimus, nemo deleniti aliquam eveniet omnis ratione beatae impedit sed, numquam quaerat iure. Animi nisi modi dolorem vero quod nemo asperiores pariatur sit sapiente.</div>
            <div>Dolor, quas molestias accusantium rem aliquam harum, quos delectus eius fugit explicabo, cupiditate. Eveniet soluta, optio quis assumenda aspernatur sunt provident voluptatem porro facere voluptatibus hic, nemo harum dicta nobis.</div>
            <div>Aspernatur enim ratione laborum repellendus omnis facilis cumque labore beatae excepturi, ipsam quia ducimus, debitis, quos iste accusamus aperiam hic magnam? Eum natus explicabo tempora eligendi quo dolore, a maiores.</div>
            <div>Odit tempora quisquam libero minus officiis dolorem laudantium quae asperiores alias sed, rem sequi ex eligendi reiciendis accusamus suscipit doloremque porro ab est minima, mollitia excepturi sit eveniet culpa. Modi.</div>
            <div>Sequi blanditiis laboriosam modi velit delectus voluptas odio tenetur earum. Culpa cumque dolorem, unde a sequi laudantium officiis, illum perspiciatis nesciunt quas temporibus impedit, voluptatem assumenda quibusdam possimus molestiae obcaecati.</div>
            <div>Distinctio minus ex eos animi maxime recusandae vel nisi molestiae asperiores eligendi natus quibusdam sit itaque quidem quam in porro, quis id iure harum earum? Rerum iure, vitae ipsam magni.</div>
            <div>Voluptate dicta consequatur fugit ea harum vero distinctio amet voluptatibus laborum omnis deleniti earum est tempore quo beatae, aut id aperiam eos obcaecati aliquid, ex, nulla nemo mollitia quaerat! Iure.</div>
            <div>Voluptates, aspernatur incidunt, distinctio quas commodi quis. Ullam eos veniam modi dolores velit eaque nisi deleniti quas nesciunt id necessitatibus, soluta optio dolore et culpa, minima, harum ipsum repellat rerum!</div>
            <div>Explicabo at porro, alias reiciendis consequatur nesciunt molestiae dolores commodi sint, suscipit, sunt repellat enim minima fugit iusto. Perspiciatis, aut. Suscipit reprehenderit culpa id modi. Dolorem voluptatum quae quod autem.</div>
            <div>Illum esse, architecto libero nostrum amet inventore repudiandae dolore consequatur iure beatae sunt distinctio eligendi quo cum reprehenderit vel ratione non aliquam impedit! Sunt sed, mollitia ipsum. Aliquam, impedit, non.</div>
            <div>Fuga saepe repudiandae obcaecati aut, ab in eius. Iste atque animi eos unde, aspernatur ex. Incidunt natus, quod, quas voluptas magni, est provident quidem et quis voluptatibus velit sed iusto.</div>
            <div>Eveniet dolore quo, possimus incidunt, necessitatibus excepturi? Nostrum debitis sed minus recusandae facere aut voluptate officia velit omnis possimus, repudiandae aperiam inventore explicabo accusantium, quisquam, impedit magnam ducimus non ex.</div>
            <div>Odit vitae sunt, ratione asperiores qui odio, sapiente saepe, illo officiis cum dolores, et dolorem quam ad iste doloribus modi distinctio eum. Iusto sequi ipsum eos debitis dolore porro expedita.</div>
            <div>Rem, optio mollitia ea reiciendis id voluptatem, quod eum facilis aliquid esse, suscipit minus quae iste, laudantium possimus deserunt vitae! Mollitia consequuntur aliquid iusto debitis fuga omnis beatae, voluptatem perferendis?</div>
            <div>Laborum aut commodi, enim id sint sunt aperiam. Quas adipisci aut inventore doloremque dignissimos repellendus sapiente iusto, laborum repudiandae quaerat, natus illum? Incidunt explicabo ducimus, id repellendus praesentium quibusdam numquam.</div>
            <div>Velit reiciendis consectetur ipsa excepturi delectus omnis sit amet, ut vero praesentium numquam non aperiam rerum sed, quia tempora. Amet necessitatibus, rem expedita nam provident. Ipsa, odit harum quisquam veritatis.</div>
            <div>Fugiat sit corporis cupiditate quo tempore magnam obcaecati, aperiam minima natus officia voluptatum odio porro libero vitae! Quae temporibus perferendis, tempore inventore nam corrupti. Architecto, atque accusamus pariatur voluptatem rerum!</div>
            <div>Itaque quo aperiam reiciendis, amet commodi earum. Ratione nulla adipisci, ea eum vitae esse harum sed, dolor alias veritatis unde eveniet consequatur. Quis, nisi! Magni culpa accusantium sequi deleniti, ratione!</div>
            <div>Eaque nisi, cupiditate cum. Obcaecati expedita culpa cumque perferendis est, iusto soluta facilis animi temporibus recusandae asperiores minima odio labore quo, deleniti id error ipsa. Dolores, consequuntur laboriosam explicabo sequi!</div>
            <div>Voluptates, id, veritatis. Quibusdam provident porro iusto doloribus quia! Dolorem, animi dignissimos aut odio suscipit distinctio consequatur commodi ipsum hic veritatis repellat accusantium, rerum a perferendis molestias quod sint fugiat.</div>
            <div>Maxime a quo, corporis rem quam necessitatibus laboriosam, quia sequi quod veritatis, repellendus quas doloremque voluptas. Aut debitis aperiam accusantium, non illo? Architecto repellendus consectetur vitae, ab esse hic laborum.</div>
            <div>Minima vero nulla aut veniam sequi ad, placeat rerum iure voluptatibus ipsam. Libero distinctio, cumque ratione, autem dolorum doloremque illum minus porro sunt ut veritatis omnis minima, vero eum adipisci.</div>
            <div>Vitae alias, hic soluta laudantium dicta facere nemo optio dolore eligendi accusantium esse neque rerum qui dolorem quaerat veniam fugit tempore temporibus. A, ex soluta sed provident tempora unde voluptate.</div>
            <div>Itaque vel eligendi suscipit voluptatem corporis quos eum alias tempore beatae eos architecto dolorem velit blanditiis molestiae repellendus sit et modi, incidunt, recusandae in? Quam nam modi itaque fugit. Voluptates.</div>
            <div>Maxime autem recusandae repellat harum quisquam officiis facere illum omnis, assumenda voluptatum ex, tempore minima magnam odit nostrum veritatis ipsa dolores delectus, vitae architecto blanditiis nihil placeat atque impedit. Error.</div>
            <div>Blanditiis dolorem asperiores dolores quaerat earum accusamus esse sapiente tempore quis qui nisi alias ex quibusdam illum iste numquam corporis voluptas accusantium, culpa optio. Illo reiciendis laborum dolorem, quae assumenda!</div>
            <div>Incidunt ad enim, optio quasi aliquid autem totam vitae, explicabo eum molestiae repudiandae odit similique iste deleniti asperiores maiores officia cumque aut facere ex. Architecto aspernatur eaque explicabo quos quod?</div>
            <div>Aut quasi accusantium eos totam labore, alias maiores tenetur possimus corporis dicta, praesentium dolores molestiae omnis sint hic reiciendis harum tempore quod, incidunt sunt quia in, inventore ducimus nobis? Expedita.</div>
            <div>Recusandae reprehenderit facilis numquam reiciendis nisi animi, ratione sint! Necessitatibus similique in atque, dolor! Quibusdam, qui ipsum dolorum beatae, libero consequuntur aspernatur cum eligendi, laborum magni maxime accusantium et, dicta.</div>
            <div>Tempora quam quasi dolore nobis nulla velit iure, voluptatum distinctio rerum. Obcaecati magni exercitationem quis sequi, molestias reprehenderit perspiciatis quam, nisi distinctio aliquid excepturi impedit? Aut cupiditate expedita, ratione voluptas!</div>
            <div>Illo doloribus facilis fugit aspernatur iure! Maxime ut temporibus est, repellat esse voluptatibus perspiciatis sed, commodi impedit laboriosam quidem, id quis illo delectus. Tempora officiis commodi quos, perferendis earum neque.</div>
            <div>Quia et magnam tempora accusantium aspernatur quaerat dolorum architecto in, labore reiciendis, nam delectus quisquam? At repellat quia ex aut, ipsam nesciunt sed nemo quisquam laborum dolores earum illo, ab.</div>
            <div>Magnam debitis autem dolorem quaerat, ipsum magni possimus assumenda laboriosam. At praesentium, ratione esse ullam eaque id non delectus enim molestias repellat quasi, laudantium a, quaerat? Consequuntur ab molestias facere.</div>
            <div>Repellat necessitatibus vel, quo praesentium ratione doloribus, sit fugit cum velit, at saepe expedita doloremque. Placeat doloremque cum quas, amet ullam asperiores tempore. Modi natus obcaecati cupiditate commodi impedit vel.</div>
            <div>Quod aliquid vitae ullam cum quia, placeat quas non iusto veritatis ut, totam reiciendis omnis commodi officiis voluptate eaque dolorum tenetur assumenda quaerat. Iste inventore cum, porro voluptates ipsum eveniet!</div>
            <div>Possimus animi quam perspiciatis voluptatum minima sed explicabo voluptate voluptatibus saepe dicta, error placeat ipsum distinctio magnam similique dolore culpa earum odit architecto. Quae doloribus laborum eaque, alias voluptate. Excepturi.</div>
            <div>Error quis officiis reprehenderit, quisquam molestias, aperiam excepturi unde similique eligendi et sunt temporibus velit eos dolores voluptatibus adipisci. Repudiandae corrupti sequi quam assumenda, optio fugit ipsum illo explicabo non!</div>
            <div>Atque totam blanditiis culpa, praesentium quae modi aut fugiat mollitia excepturi delectus illo provident quas, aliquid voluptate eius quasi aperiam similique maxime. Aliquid natus unde rerum itaque consequatur accusantium fugit.</div>
            <div>Ducimus voluptate aliquam sequi! Aspernatur excepturi dolorum cumque eum neque nulla sunt porro, sapiente illum, odit, reprehenderit corporis ipsam veritatis totam blanditiis voluptatem nam optio at impedit eveniet. Esse, modi.</div>
            <div>Tempora labore maiores explicabo iusto tempore provident, debitis. Voluptatum eligendi cum deserunt maxime suscipit minima sit quibusdam provident in molestiae, tempore voluptas error quidem tenetur nam doloremque, cumque? Molestiae, labore!</div>
            <div>Repudiandae impedit officiis, vel unde fuga eaque voluptates deserunt explicabo neque dignissimos nam ipsam perspiciatis nesciunt quod mollitia debitis incidunt dicta eligendi, expedita doloremque. Natus pariatur impedit eveniet officia tenetur!</div>
            <div>Impedit dolorum, quam eos asperiores possimus alias, autem quos aliquam beatae. Doloribus labore at quisquam cum nulla possimus, sapiente ullam porro voluptatum amet totam harum voluptas delectus maxime aliquam, error.</div>
            <div>Nihil nostrum harum possimus repellendus laudantium voluptatem ipsum quisquam, dignissimos porro alias. Temporibus esse dolores fuga sapiente adipisci expedita autem doloribus omnis. Error consequuntur, doloribus accusantium iure impedit asperiores vitae?</div>
            <div>Assumenda labore officiis cupiditate nostrum iste voluptate repudiandae laborum beatae! Similique eius totam laudantium quas. Provident, veritatis perferendis magni unde itaque labore nisi iusto odio minima, est, non quia omnis.</div>
            <div>Similique culpa ad nihil quam voluptates quibusdam at, pariatur natus nulla, sapiente hic voluptate, tenetur veritatis modi neque sint beatae! Nam veniam, ullam cupiditate totam perspiciatis blanditiis eaque doloribus, error.</div>
            <div>Harum laboriosam cupiditate eveniet quas earum totam vel quos, aut iste iusto quibusdam laudantium, deleniti sit soluta tempora libero voluptas ipsum autem itaque enim nesciunt! Nisi soluta accusamus sint dignissimos.</div>
            <div>Nemo odit nulla vero autem tempore consequatur possimus fugiat molestias error aut modi obcaecati inventore, neque nostrum asperiores, sed atque voluptatibus fuga expedita alias consequuntur architecto nisi ab! Aut, illo.</div>
            <div>Possimus sed dolor eligendi, labore rerum eius aperiam voluptatem, aspernatur magnam ipsa quidem error, unde delectus dolorum, blanditiis modi quo expedita soluta magni. Fuga omnis quo eius porro corporis cumque.</div>
            <div>Vel eos perferendis, officiis a labore, laborum dicta atque est laudantium ex dolorum doloremque culpa error earum dignissimos quisquam fugiat autem voluptatem nobis nostrum ipsa non corporis aliquam. Dolores, impedit.</div>
            <div>Odio animi quaerat autem placeat id, quasi doloribus dicta modi, ducimus nisi, ab voluptas labore exercitationem. Molestias, dolor illum, ab eveniet voluptates laudantium magni reiciendis commodi sit, quasi consectetur, facilis.</div>
            <div>Minus suscipit dicta inventore eaque quas ipsam, mollitia facere unde excepturi animi. Natus et accusantium, eveniet voluptates voluptatum voluptatem officia excepturi est veritatis? Dolor, vitae facilis eligendi, impedit dicta deleniti.</div>
            <div>Debitis placeat aliquid veniam vero sint maiores adipisci fuga animi provident vel nobis dolores totam ab, excepturi a quidem quo earum commodi dicta minima nesciunt accusamus quibusdam, sunt sed. Ipsum.</div>
            <div>Aliquam facilis optio ullam ad corporis voluptatibus, architecto qui totam consequuntur! Reprehenderit debitis corporis veniam nostrum. Vel tempore vero, sed ratione fuga nam odio sapiente sint placeat, commodi animi sit!</div>
            <div>Libero quisquam, laborum autem eum voluptas consequatur! Fugit nisi repellat, vitae similique sequi fugiat mollitia culpa et quas veritatis sed repellendus numquam inventore, recusandae, ipsam iusto dolorum consectetur blanditiis nulla.</div>
            <div>Ratione maxime, possimus ad necessitatibus atque, soluta obcaecati vitae vero ex, accusantium quo perspiciatis assumenda. Nesciunt exercitationem beatae quasi. Obcaecati aperiam aliquam magni sunt. Tempora officia maiores non voluptatem veritatis.</div>
            <div>Nulla explicabo esse, dolores dolore inventore hic sit. Possimus animi, accusamus sunt veniam deserunt maiores neque molestias libero itaque quibusdam soluta repellendus est eligendi placeat beatae, vitae iure aut perferendis.</div>
            <div>Excepturi nulla, itaque culpa. Laboriosam atque, at impedit in fugiat aut, perspiciatis sunt optio sapiente porro expedita! Deleniti ipsa, sed architecto quia odit molestias neque, nesciunt a sapiente quas rerum.</div>
            <div>Aliquid repudiandae doloribus fuga exercitationem, quo magni ut, aut ratione consectetur rem, neque! Qui, sed, maxime. Maxime sapiente numquam, maiores. Officiis soluta labore asperiores est, odit molestiae non atque sequi.</div>
            <div>Voluptatum quis perferendis ratione deserunt nihil, illo eaque quos nostrum dolor numquam necessitatibus consequuntur nam veritatis dolores, repellat distinctio dolorum voluptatem vitae, magnam aperiam reprehenderit optio dignissimos. Ex, quia beatae?</div>
            <div>Nam autem nobis hic doloremque laudantium voluptatibus, molestiae ipsa, inventore! Laudantium distinctio quibusdam nulla! Asperiores nemo, autem neque? Magnam voluptatum doloremque nostrum placeat repellat dolor accusamus totam ea, rem autem!</div>
            <div>Aliquid iste nihil consectetur atque ipsa modi, natus rem sequi quia at laudantium obcaecati voluptate ad, perferendis. Voluptas velit, harum expedita sapiente, cum qui ab, necessitatibus in quibusdam rem consequuntur.</div>
            <div>Quod, doloremque, non placeat rerum iure eaque numquam officia explicabo alias dicta officiis ad. Maiores, perspiciatis. Mollitia et reprehenderit exercitationem quod, non in qui sed? Earum quis molestias inventore amet.</div>
            <div>Itaque libero, corporis modi, enim tempora optio cum doloremque molestias, fugit exercitationem quas quisquam rerum quibusdam quae, eius autem. Sed cum quod deleniti praesentium mollitia cumque facere ipsum at in.</div>
          </p>
        </Scrollbars>
      </div>
    );
  }
}

export default MainContainer;